### ISSUE TITLE
Vue-packery is slow with vue-router. Packery needs to be destroyed on unbind.

### ISSUE THREAD

**Issue by muerwre** [t-k-f/vue-packery-plugin#1]
I've found that while using vue-packery-plugin with vue-router it works slower and slower every time i'm accessing packery component. 

I'm not pro developer, but i've opened editor and force it to destroy packery every time component unbinds:

```
// const packery = new Packery(el, binding.value)
// replaced it with:
el.packery = new Packery(el, binding.value);
```

Now i can access packery from unbind component. After this i've added unbind event to directive: 
```
unbind(el){
   el.packery.destroy();
   el.packery = null;
}
```
And added a string to nextTick, so it will not run after element unbind:
```
Vue.nextTick(() =>
 {
        if(! el.packery) return;
```
Using isLayoutInstant: true to v-packery object i'm getting much faster performance.

**Comment by muerwre** [comment]
I see you've added unbind property, but fix is incomplete. I've got this error on leaving component in vue router:
```
components.js?48266:4854 TypeError: Cannot read property 'destroy' of undefined
    at unbind (components.js?48266:15566)
    at callHook$1 (components.js?48266:9301)
    at _update (components.js?48266:9265)
    at updateDirectives (components.js?48266:9207)
    at Array.unbindDirectives (components.js?48266:9201)
    at invokeDestroyHook (components.js?48266:8770)
    at invokeDestroyHook (components.js?48266:8774)
    at invokeDestroyHook (components.js?48266:8774)
    at invokeDestroyHook (components.js?48266:8774)
    at VueComponent.patch [as __patch__] (components.js?48266:9092)
```

Please, add this string: 
```
if(! el.packery) return;
```
In packeryDraw:
```            
const packeryDraw = () =>
            {   
                Vue.nextTick(() =>
                {   
                    if(! el.packery) return; // This string!
                    packery.reloadItems()
                    packery.layout()
                })
            }
```
Thank you for your work :-)

**Comment by jan-thoma** [comment]
Now we have a correct check if parent node is still present, and if it's the parent node of the emitting child

**Comment by muerwre** [comment]
Thank you :-)
