### ISSUE TITLE
import error with nuxt

### ISSUE THREAD

**Issue by ManUtopiK** [t-k-f/vue-packery-plugin#10]
With `import {packeryEvents} from 'vue-packery-plugin'` on a component, nuxt throw an error:   `window is not defined`

I load vue-packery with ssr: false from nuxt.config.js.

How could I do to import packeryEvents?

**Comment by jan-thoma** [comment]
window is apparently not present on server side. if you import the eventBus in your component you need to take care of this problem inside the component.

This is not a issue of this package rather than Vue SSR

**Comment by usb248** [comment]
it's up to the plugin to take care when calling the window object.... and manage SSR correctly... it's not a Vue SSR problem :man_facepalming:

**Comment by jan-thoma** [comment]
That's maybe true... anyway this plugin is no longer maintained as it's written in the readme.

**Comment by usb248** [comment]
It's true ;)
