### ISSUE TITLE
Annoying console.log()

### ISSUE THREAD

**Issue by ManUtopiK** [t-k-f/vue-packery-plugin#11]
[`console.log()`](https://github.com/t-k-f/vue-packery-plugin/blob/b65ff5196c6a15da730b52344b2276d2399e4edb/src/index.js#L86) added with [this commit](https://github.com/t-k-f/vue-packery-plugin/commit/c7e43d80b2c83739a51005e17b2d149e26fb7fe8)

**Comment by jan-thoma** [comment]
fixed
