### ISSUE TITLE
Possible Packery GPL-3.0 license conflict

### ISSUE THREAD

**Issue by torss** [t-k-f/vue-packery-plugin#13]
Seems like this package uses <https://www.npmjs.com/package/packery>, which is licensed under the viral `GPL-3.0` (the author has dual-licensed it, with commercial licenses being available <https://packery.metafizzy.co/>), so it might be that this currently `MIT`-licensed package legally needs to change to `GPL-3.0` (or something compatible) too. This is also the understanding / intent of the author according to <https://packery.metafizzy.co/license.html>: "Releasing your project that uses Packery under the GPLv3, in turn, requires your project to be licensed under the GPLv3.".

_(But IANAL and personally don't use this package at the moment, so feel free to close the issue immediately and without response; just thought I would let you know.)_

**Comment by jan-thoma** [comment]
You're right. I changed the License according to GPL-3.0 compliance.
