### ISSUE TITLE
How to Trigger "Layout" from button click in component?

### ISSUE THREAD

**Issue by tophat1986** [t-k-f/vue-packery-plugin#5]
I've got this working nicely.  Thank you.

But any ideas on how to call "layout" to re-draw the grid contents in Vue JS and specifically from a component?  I have divs that are changing size on a button click and need to call the below to trigger packery to re-layout the contents so it's not overlapping.

https://packery.metafizzy.co/methods.html#layout-packery

Help appreciated.  Thanks!

**Comment by jan-thoma** [comment]
Closed as an exact duplicate of #3
